### ISSUE TITLE
Usage doc

### ISSUE THREAD

**Issue by kaushikbalasundar** [Alex-Beh/realsense_yolo#5]
Hello! 

I am trying to achieve the same with 3d person tracking with YOLO, spencer and realsense d435i. Could you please update the usage for me test out and understand how it works?

**Comment by Alex-Beh** [comment]
Hello, thanks for your interest on this repo. I am doing a code cleaning recently and push the code with README.md to the branch [code_cleaning](https://github.com/Alex-Beh/realsense_yolo/tree/code_cleaning). Will do the code testing tomorrow to make sure there is no syntax error and it works as before.

May I know which YOLO repo you using? Besides, where you running the detection mode? A personal laptop or some single board computer such as Nvidia xavier NX or Intel NUC?

**Comment by kaushikbalasundar** [comment]
Thanks for your response, and for updating the usage! I am running this on an Intel NUC in a mobile robot, and hope to integrate it with the spencer people tracking package, as a substitute to the upper body detector which isn't as robust and tends to crash occasionally. I believe your use-case is also similar? If yes, I would also appreciate any advice on how you integrated this as a substitute to the upper body detector.

**Comment by Alex-Beh** [comment]
Yes I think we both have the similar use-case. You might not able to use the tensorRT deep learning optimizer. You can use the [dnn_detect](http://wiki.ros.org/dnn_detect) and set [mobilenetssd](    <arg name="mobilenetssd"   default="false"/>) flag to true.

Then ` roslaunch realsense_yolo realsense_yolo.launch`. Let me know any issue you face for the code compilation.

**Comment by kaushikbalasundar** [comment]
Thanks for your response. Trying to compile your code - I removed the tensorRT dependencies and CUDA references in the CMakeLists.txt. However, I am facing the following error during compilation. Your master branch compiled properly however for me.  

CMakeFiles/mobilessd_adaptor.dir/src/realsense_yolo.cpp.o: In function `realsense_yolo::realsense_yolo_detector::filterOutUnwantedDetections(boost::shared_ptr<realsense_yolo::BoundingBoxes3d_<std::allocator<void> > const> const&, boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&)':
realsense_yolo.cpp:(.text+0x1d87): undefined reference to `cv_bridge::toCvCopy(boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/mobilessd_adaptor.dir/src/realsense_yolo.cpp.o: In function `message_filters::Connection message_filters::Signal9<realsense_yolo::BoundingBoxes3d_<std::allocator<void> >, sensor_msgs::Image_<std::allocator<void> >, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType>::addCallback<boost::shared_ptr<realsense_yolo::BoundingBoxes3d_<std::allocator<void> > const> const&, boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&>(boost::function<void (boost::shared_ptr<realsense_yolo::BoundingBoxes3d_<std::allocator<void> > const> const&, boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&)> const&)':
realsense_yolo.cpp:(.text._ZN15message_filters7Signal9IN14realsense_yolo16BoundingBoxes3d_ISaIvEEEN11sensor_msgs6Image_IS3_EENS_8NullTypeES8_S8_S8_S8_S8_S8_E11addCallbackIRKN5boost10shared_ptrIKS4_EERKNSC_IKS7_EERKNSC_IKS8_EESO_SO_SO_SO_SO_SO_EENS_10ConnectionERKNSB_8functionIFvT_T0_T1_T2_T3_T4_T5_T6_T7_EEE[_ZN15message_filters7Signal9IN14realsense_yolo16BoundingBoxes3d_ISaIvEEEN11sensor_msgs6Image_IS3_EENS_8NullTypeES8_S8_S8_S8_S8_S8_E11addCallbackIRKN5boost10shared_ptrIKS4_EERKNSC_IKS7_EERKNSC_IKS8_EESO_SO_SO_SO_SO_SO_EENS_10ConnectionERKNSB_8functionIFvT_T0_T1_T2_T3_T4_T5_T6_T7_EEE]+0x191): undefined reference to `message_filters::Connection::Connection(boost::function<void ()> const&)'
CMakeFiles/mobilessd_adaptor.dir/src/realsense_yolo.cpp.o: In function `message_filters::Synchronizer<message_filters::sync_policies::ApproximateTime<realsense_yolo::BoundingBoxes3d_<std::allocator<void> >, sensor_msgs::Image_<std::allocator<void> >, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType> >::disconnectAll()':
realsense_yolo.cpp:(.text._ZN15message_filters12SynchronizerINS_13sync_policies15ApproximateTimeIN14realsense_yolo16BoundingBoxes3d_ISaIvEEEN11sensor_msgs6Image_IS5_EENS_8NullTypeESA_SA_SA_SA_SA_SA_EEE13disconnectAllEv[_ZN15message_filters12SynchronizerINS_13sync_policies15ApproximateTimeIN14realsense_yolo16BoundingBoxes3d_ISaIvEEEN11sensor_msgs6Image_IS5_EENS_8NullTypeESA_SA_SA_SA_SA_SA_EEE13disconnectAllEv]+0x43): undefined reference to `message_filters::Connection::disconnect()'
CMakeFiles/mobilessd_adaptor.dir/src/realsense_yolo.cpp.o: In function `message_filters::Connection message_filters::SimpleFilter<realsense_yolo::BoundingBoxes3d_<std::allocator<void> > >::registerCallback<ros::MessageEvent<realsense_yolo::BoundingBoxes3d_<std::allocator<void> > const> const&>(boost::function<void (ros::MessageEvent<realsense_yolo::BoundingBoxes3d_<std::allocator<void> > const> const&)> const&)':
realsense_yolo.cpp:(.text._ZN15message_filters12SimpleFilterIN14realsense_yolo16BoundingBoxes3d_ISaIvEEEE16registerCallbackIRKN3ros12MessageEventIKS4_EEEENS_10ConnectionERKN5boost8functionIFvT_EEE[_ZN15message_filters12SimpleFilterIN14realsense_yolo16BoundingBoxes3d_ISaIvEEEE16registerCallbackIRKN3ros12MessageEventIKS4_EEEENS_10ConnectionERKN5boost8functionIFvT_EEE]+0xba): undefined reference to `message_filters::Connection::Connection(boost::function<void ()> const&)'
CMakeFiles/mobilessd_adaptor.dir/src/realsense_yolo.cpp.o: In function `message_filters::Connection message_filters::SimpleFilter<sensor_msgs::Image_<std::allocator<void> > >::registerCallback<ros::MessageEvent<sensor_msgs::Image_<std::allocator<void> > const> const&>(boost::function<void (ros::MessageEvent<sensor_msgs::Image_<std::allocator<void> > const> const&)> const&)':
realsense_yolo.cpp:(.text._ZN15message_filters12SimpleFilterIN11sensor_msgs6Image_ISaIvEEEE16registerCallbackIRKN3ros12MessageEventIKS4_EEEENS_10ConnectionERKN5boost8functionIFvT_EEE[_ZN15message_filters12SimpleFilterIN11sensor_msgs6Image_ISaIvEEEE16registerCallbackIRKN3ros12MessageEventIKS4_EEEENS_10ConnectionERKN5boost8functionIFvT_EEE]+0xba): undefined reference to `message_filters::Connection::Connection(boost::function<void ()> const&)'
collect2: error: ld returned 1 exit status
realsense_yolo/CMakeFiles/mobilessd_adaptor.dir/build.make:179: recipe for target '/home/dfl-nuc/temp_ws/devel/lib/realsense_yolo/mobilessd_adaptor' failed
make[2]: *** [/home/dfl-nuc/temp_ws/devel/lib/realsense_yolo/mobilessd_adaptor] Error 1
CMakeFiles/Makefile2:706: recipe for target 'realsense_yolo/CMakeFiles/mobilessd_adaptor.dir/all' failed
make[1]: *** [realsense_yolo/CMakeFiles/mobilessd_adaptor.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/realsense_yolo.dir/src/realsense_yolo.cpp.o: In function `realsense_yolo::realsense_yolo_detector::filterOutUnwantedDetections(boost::shared_ptr<realsense_yolo::BoundingBoxes3d_<std::allocator<void> > const> const&, boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&)':
realsense_yolo.cpp:(.text+0x1d87): undefined reference to `cv_bridge::toCvCopy(boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/realsense_yolo.dir/src/realsense_yolo.cpp.o: In function `message_filters::Connection message_filters::Signal9<realsense_yolo::BoundingBoxes3d_<std::allocator<void> >, sensor_msgs::Image_<std::allocator<void> >, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType>::addCallback<boost::shared_ptr<realsense_yolo::BoundingBoxes3d_<std::allocator<void> > const> const&, boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&>(boost::function<void (boost::shared_ptr<realsense_yolo::BoundingBoxes3d_<std::allocator<void> > const> const&, boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&, boost::shared_ptr<message_filters::NullType const> const&)> const&)':
realsense_yolo.cpp:(.text._ZN15message_filters7Signal9IN14realsense_yolo16BoundingBoxes3d_ISaIvEEEN11sensor_msgs6Image_IS3_EENS_8NullTypeES8_S8_S8_S8_S8_S8_E11addCallbackIRKN5boost10shared_ptrIKS4_EERKNSC_IKS7_EERKNSC_IKS8_EESO_SO_SO_SO_SO_SO_EENS_10ConnectionERKNSB_8functionIFvT_T0_T1_T2_T3_T4_T5_T6_T7_EEE[_ZN15message_filters7Signal9IN14realsense_yolo16BoundingBoxes3d_ISaIvEEEN11sensor_msgs6Image_IS3_EENS_8NullTypeES8_S8_S8_S8_S8_S8_E11addCallbackIRKN5boost10shared_ptrIKS4_EERKNSC_IKS7_EERKNSC_IKS8_EESO_SO_SO_SO_SO_SO_EENS_10ConnectionERKNSB_8functionIFvT_T0_T1_T2_T3_T4_T5_T6_T7_EEE]+0x191): undefined reference to `message_filters::Connection::Connection(boost::function<void ()> const&)'
CMakeFiles/realsense_yolo.dir/src/realsense_yolo.cpp.o: In function `message_filters::Synchronizer<message_filters::sync_policies::ApproximateTime<realsense_yolo::BoundingBoxes3d_<std::allocator<void> >, sensor_msgs::Image_<std::allocator<void> >, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType, message_filters::NullType> >::disconnectAll()':
realsense_yolo.cpp:(.text._ZN15message_filters12SynchronizerINS_13sync_policies15ApproximateTimeIN14realsense_yolo16BoundingBoxes3d_ISaIvEEEN11sensor_msgs6Image_IS5_EENS_8NullTypeESA_SA_SA_SA_SA_SA_EEE13disconnectAllEv[_ZN15message_filters12SynchronizerINS_13sync_policies15ApproximateTimeIN14realsense_yolo16BoundingBoxes3d_ISaIvEEEN11sensor_msgs6Image_IS5_EENS_8NullTypeESA_SA_SA_SA_SA_SA_EEE13disconnectAllEv]+0x43): undefined reference to `message_filters::Connection::disconnect()'
CMakeFiles/realsense_yolo.dir/src/realsense_yolo.cpp.o: In function `message_filters::Connection message_filters::SimpleFilter<realsense_yolo::BoundingBoxes3d_<std::allocator<void> > >::registerCallback<ros::MessageEvent<realsense_yolo::BoundingBoxes3d_<std::allocator<void> > const> const&>(boost::function<void (ros::MessageEvent<realsense_yolo::BoundingBoxes3d_<std::allocator<void> > const> const&)> const&)':
realsense_yolo.cpp:(.text._ZN15message_filters12SimpleFilterIN14realsense_yolo16BoundingBoxes3d_ISaIvEEEE16registerCallbackIRKN3ros12MessageEventIKS4_EEEENS_10ConnectionERKN5boost8functionIFvT_EEE[_ZN15message_filters12SimpleFilterIN14realsense_yolo16BoundingBoxes3d_ISaIvEEEE16registerCallbackIRKN3ros12MessageEventIKS4_EEEENS_10ConnectionERKN5boost8functionIFvT_EEE]+0xba): undefined reference to `message_filters::Connection::Connection(boost::function<void ()> const&)'
CMakeFiles/realsense_yolo.dir/src/realsense_yolo.cpp.o: In function `message_filters::Connection message_filters::SimpleFilter<sensor_msgs::Image_<std::allocator<void> > >::registerCallback<ros::MessageEvent<sensor_msgs::Image_<std::allocator<void> > const> const&>(boost::function<void (ros::MessageEvent<sensor_msgs::Image_<std::allocator<void> > const> const&)> const&)':
realsense_yolo.cpp:(.text._ZN15message_filters12SimpleFilterIN11sensor_msgs6Image_ISaIvEEEE16registerCallbackIRKN3ros12MessageEventIKS4_EEEENS_10ConnectionERKN5boost8functionIFvT_EEE[_ZN15message_filters12SimpleFilterIN11sensor_msgs6Image_ISaIvEEEE16registerCallbackIRKN3ros12MessageEventIKS4_EEEENS_10ConnectionERKN5boost8functionIFvT_EEE]+0xba): undefined reference to `message_filters::Connection::Connection(boost::function<void ()> const&)'
collect2: error: ld returned 1 exit status
realsense_yolo/CMakeFiles/realsense_yolo.dir/build.make:179: recipe for target '/home/dfl-nuc/temp_ws/devel/lib/realsense_yolo/realsense_yolo' failed
make[2]: *** [/home/dfl-nuc/temp_ws/devel/lib/realsense_yolo/realsense_yolo] Error 1
CMakeFiles/Makefile2:535: recipe for target 'realsense_yolo/CMakeFiles/realsense_yolo.dir/all' failed
make[1]: *** [realsense_yolo/CMakeFiles/realsense_yolo.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j12 -l12" failed

**Comment by kaushikbalasundar** [comment]
Could you also tell me what changes are to be made to the spencer package to replace the upper body detector with yours?

**Comment by Alex-Beh** [comment]
@kaushikbalasundar May I know your opencv version and rosdistro? Do you manage to compile the code successfully?

**Comment by kaushikbalasundar** [comment]
I haven't been able to compile it yet. I am using ROS Melodic with OpenCV 3.2.0. Would this work only with 3.4.11?

**Comment by kaushikbalasundar** [comment]
I got the darknet_yolo from your master branch working. Its now publishing messages under /spencer/perception_internal/detected_persons/rgbd_front_top/upper_body

Can you please give me some pointers on how you integrated these detections with the tracking? The raw detections are being visually confirmed in my case.

**Comment by Alex-Beh** [comment]
I fixed the issue on the code_cleaning branch temporarily. I don't know why the find_package() don't work in this case so currently I hardcore the library path in the CMakeLists.txt ([message_filters & cv_bridge](https://github.com/Alex-Beh/realsense_yolo/blob/0fb3c0103a5f7561792b763fa5f3bd68b5799a5c/CMakeLists.txt#L118). You can try to compile this branch and let me know again.

**How to integrate this detectors into the specer framework:**
Don't launch this [front_rgbd_detectors.launch](https://github.com/spencer-project/spencer_people_tracking/blob/master/launch/spencer_people_tracking_launch/launch/detectors/front_rgbd_detectors.launch) and launch the detector from this package. And check the output from `rostopic echo /spencer/perception_internal/detected_persons/rgbd_front_top/upper_body` to see whether the detection result has been imported into spencer framework.

May I know which launch file you used to start the spencer framework? Are you using the lidar detector?

**Comment by kaushikbalasundar** [comment]
Thank you for your response. I am still getting the same error unfortunately. Why have you mentioned 3.4.11 EXACT? Does this not work with 3.2.0? 

I am using tracking_single_rgbd_sensor.launch, and removed the front_rgbd_detectors.launch, and instead using your detector as you suggested. Using your master branch's code, I was able to compile this properly, /spencer/perception_internal/detected_persons/rgbd_front_top/upper_body is receiving messages. However, when I run tracking, the visually confirmed tracks topic where the output of tracking is supposed be does not seem to work. /spencer/perception/tracked_persons_confirmed_by_upper_body/spencer/perception/tracked_persons_confirmed_by_upper_body is empty.

Why could this be? Also I check that remapping is happening fine because data is being published into the fused detections: /spencer/perception/detected_persons/

**Comment by Alex-Beh** [comment]
Have you git pull the latest code? It should work with 3.2.0 also.

I think you have commited out those code ([here](https://github.com/dfl-rlab/spencer_people_tracking/commit/72f67a86eb5059deb1eba6bdebe2ebf1cb69f9fb)). You can check the rostopic msg from `/spencer/perception/tracked_persons` .

**Comment by kaushikbalasundar** [comment]
Yes, I cloned the repository from scratch and tried it out. I had to remove some lines from the CMakeLists.txt to avoid looking for tensorRT related packages and CUDA related dependencies. However, I am still unable to compile it. 

You're right, I have commented those lines out because it caused the tracking to crash. However, when using the upper_body_detector, this doesn't seem to cause a problem, and the tracking works fine. My YOLO detection FPS is very low at 1.4 FPS, so I'm trying this again on a CUDA based system to see if anything changes.

**Comment by kaushikbalasundar** [comment]
Apart from not launching front_rgbd_detectors.launch , did you make any other changes for tracking to work? I verified that detection output is being received in by using `rostopic echo /spencer/perception_internal/detected_persons/rgbd_front_top/upper_body`. However, the tracking topic `/spencer/perception/tracked_persons_confirmed_by_upper_body` is empty. Detection is publishing at 9-10 Hz approximately. Could this be a reason? I verified that the detection on the same topic when using upper body detector is about 30 Hz.

**Comment by Alex-Beh** [comment]
9-10Hz should be okay. Is there any messages in /spencer/perception/tracked_persons? There is no messages in tracked_persons_confirmed_by_upper_body if you commented the code in https://github.com/dfl-rlab/spencer_people_tracking/commit/72f67a86eb5059deb1eba6bdebe2ebf1cb69f9fb.

You can send me a rosbag file and I can look into it when I am free.
